name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set Xcode 15.4
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.4.app

      - name: iOS Build 
        run: |
          xcodebuild \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'

      - name: macOS Build 
        run: |
          xcodebuild \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk macosx \
            -destination 'platform=macosx' \

      - name: tvOS Build 
        run: |
          xcodebuild \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk appletvsimulator \
            -destination 'platform=tvOS Simulator,name=Apple TV' \

      - name: xrOS Build 
        run: |
          xcodebuild \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk xrsimulator \
            -destination 'platform=visionOS Simulator,name=Apple Vision Pro' \

      - name: iOS Tests
        run: |
          xcodebuild test \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.5'

      - name: macOS Tests
        run: |
          xcodebuild \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk macosx \
            -destination 'platform=macosx' \
            test

      - name: tvOS Tests
        run: |
          xcodebuild \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk appletvsimulator \
            -destination 'platform=tvOS Simulator,name=Apple TV' \
            test

      - name: visionOS Tests
        run: |
          xcodebuild \
            -project AnalyticsConnector.xcodeproj \
            -scheme AnalyticsConnector \
            -sdk xrsimulator \
            -destination 'platform=visionOS Simulator,name=Apple Vision Pro' \
            test
